stages:
    - dev
    - test


image: ansible/centos7-ansible


.run_playbook:
    allow_failure: false
    tags:
        - aws
    script:
        - ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa 2>/dev/null <<< y >/dev/null
        - ansible-playbook playbook.yml -u ec2-user --private-key=~/.ssh/id_rsa -i $inventory -e "app_servers=$hosts"

deploy_dev:
    extends: .run_playbook
    variables:
        inventory: inventory
        hosts: dev 
    stage: dev
    environment:
        name: Dev
        
deploy_test:
    extends: .run_playbook
    variables:
        inventory: inventory
        hosts: test 
    stage: test
    environment:
        name: Test