
stages:
    - dev
    - test


image: ansible/centos7-ansible


.run_playbook:
    allow_failure: false
    script:
        - ansible localhost -m ping

deploy_dev:
    extends: .run_playbook
    variables:
        inventory: inventory
        hosts: dev 
    stage: dev
    environment:
        name: Dev
        
deploy_test:
    extends: .run_playbook
    variables:
        inventory: inventory
        hosts: test 
    stage: test
    environment:
        name: Test