stages:
    - dev
    - test


image: ansible/centos7-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'

.run_playbook:
    allow_failure: false
    tags:
        - aws
    script:
        - ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa 2>/dev/null <<< y >/dev/null
        - echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
        - echo $SSH_PRIVATE_KEY | tr ' ' '\n' | tail -n+5 | head -n-4 >> ~/.ssh/id_rsa
        - echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
        - eval $(ssh-agent -s)
        - cat ~/.ssh/id_rsa 
        - ls -la ~/.ssh/
        - ssh -o "StrictHostKeyChecking=no" automation@ip-172-31-0-203.eu-west-1.compute.internal -vvv -i ~/.ssh/id_rsa cat /etc/hosts 
        - ansible-playbook playbook.yml -u automation --private-key=~/.ssh/id_rsa -i $inventory -e "app_servers=$hosts"

deploy_dev:
    extends: .run_playbook
    variables:
        inventory: inventory
        hosts: dev 
    stage: dev
    environment:
        name: Dev
        
deploy_test:
    extends: .run_playbook
    variables:
        inventory: inventory
        hosts: test 
    stage: test
    environment:
        name: Test