---


-  name: Run deploy
   hosts: "{{app_servers}}"
   become: yes
   roles:
      - wildfly
   tasks:
      - name: Deploy built application
        copy:
          dest: /usr/share/jboss-as/standalone/deployments/sample-app.war
          src: SampleWebApp.war
      