---


-  name: Run deploy
   hosts: "{{app_servers}}"
   become: yes
   roles:
      - wildfly
      - { role: geerlingguy.nginx }
   tasks:
      - file:
          path: /tmp/hello
          state: touch
      - command: " cat /etc/hosts"