
all:
    hosts:
    vars: 
        ansible_python_interpreter: /usr/bin/python
    children:
      dev:
        hosts:
          ip-172-31-0-203.eu-west-1.compute.internal:
        vars:
            wildfly_version: 20.0.0.Final
      test:
        hosts:
          ip-172-31-0-219.eu-west-1.compute.internal:
        vars:
            wildfly_version: 20.0.0.Final
      prod:
        hosts:
