---
all:
    children:
        dev:
            hosts:
                ip-172-31-0-83.eu-west-1.compute.internal:
        test:
            hosts:
                localhost:
        prod:
            hosts:
