---
all:
    children:
        dev:
            hosts:
                ec2-54-72-205-26.eu-west-1.compute.amazonaws.com:
        test:
            hosts:
                localhost:
        prod:
            hosts:
